### ISSUE TITLE
Problem setting up iOS build on Mac

### ISSUE THREAD

**Issue by colingor** [edina/fieldtrip-open#74]
Running:

``` fab install_project:ios```

results in the following error:

>Adding ios project...
execvp(): Permission denied
Error: /Users/colin/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/create: Command failed with exit code EACCES
    at ChildProcess.whenDone (/Users/colin/Code/STSWorkspaces/Workspace1/git/fieldtrip_ios/fieldtrip-open/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:795:12)
Fatal error: local() encountered an error (return code 1) while executing 'cordova platform add ios@3.9.2'

**Comment by colingor** [comment]
The wrong version of Cordova had been specified in the config.ini I had been using to build the iOS version of the app.  This is likely what caused this problem.
